[build]
  publish = "public"
#  command = "hugo --minify"
  command = "hugo --gc --minify"
#  command = "hugo --cleanDestinationDir --gc --minify"

[dev]
  command = "hugo server --disableFastRender --gc --minify"

[deploy]
  command = "netlify deploy --prod --dir=public"


[[redirects]]
  from = "https://travy.me/*"
  to = "https://travy.id/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.travy.me/*"
  to = "https://travy.id/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.travy.id/*"
  to = "https://travy.id/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://travyweb.netlify.app/*"
  to = "https://travy.id/:splat"
  status = 301
  force = true


[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404


#[[plugins]]
#  package = "netlify-plugin-hugo-cache-resources"
#    [plugins.inputs]
#    # If it should show more verbose logs (optional, default = true)
#    debug = true


[[plugins]]
  package = "netlify-plugin-inline-critical-css"